In [1]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5]
arr=np.array(my_lst)
#this converts a list into an array using the inbuilt function in numpy

In [8]:
print (arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [ ]:
arr.shape()

In [14]:
#multinested array
my_lst1=[1,2,3]
my_lst2=[4,5,6]
my_lst3=[7,8,9]

In [16]:
arr=np.array([my_lst1,my_lst2,my_lst3])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape

(3, 3)

In [22]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [24]:
arr[3]

4

In [27]:
#if 2 dimensional array
my_lst1=[1,2,3]
my_lst2=[4,5,6]
my_lst3=[7,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [28]:
arr[:,:]
#this picks up all the elements


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr[0:2,:]
#this picks up 1st and 2nd row

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr[0:2,0:2]
#this picks up 1 and 2nd row and column

array([[1, 2],
       [4, 5]])

In [33]:
arr[1:,2:]
#this picks up only 6 and 9

array([[6],
       [9]])

In [34]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [49]:
arr[1:3,2:4]
#assignment by him

array([[4, 5],
       [6, 8]])

In [55]:
arr=np.arange(0,10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [58]:
arr[3:]=100

In [60]:
val =2
arr[arr<val]

array([0, 1])

In [61]:
arr*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [62]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [66]:
np.ones((2,5),dtype=int)
#by default dtype is float

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
np.random.rand(3,3)

array([[0.80147151, 0.34018245, 0.08432774],
       [0.76163241, 0.10873692, 0.69413611],
       [0.54705858, 0.34543372, 0.33646171]])

In [70]:
np.random.randn(3,3)
#makes an array of random variables from standarad normal distribution

array([[-1.69667542, -1.72469106, -1.18051048],
       [ 1.39953804,  0.38520771, -0.12116447],
       [-0.15469917, -1.52077794,  0.49798417]])